clock:
  initial-seconds: 300
  increment-seconds: 3
start:
  wait-seconds: 60
disconnect:
  loss-seconds: 30
bet:
  min-amount: 100.0
  max-amount: 1000.0
debug:
  turn-logging: false
piece:
  king:
    white: 0.5
    black: 0.5
  queen:
    white: 0.5
    black: 0.5
  rook:
    white: 0.6
    black: 0.6
  bishop:
    white: 0.6
    black: 0.6
  knight:
    white: 0.5
    black: 0.5
  pawn:
    white: 0.8
    black: 0.8
  default:
    white: 0.25
    black: 0.25
rotation: # 1-4
  king:
    white: 0
    black: 0
  queen:
    white: 0
    black: 0
  rook:
    white: 0
    black: 0
  bishop:
    white: 0
    black: 0
  knight:
    white: 0
    black: 2
  pawn:
    white: 0
    black: 0
  default:
    white: 0
    black: 0
offset:
  king:
    white: 0.22
    black: 0.22
  queen:
    white: 0.22
    black: 0.22
  rook:
    white: 0.262
    black: 0.262
  bishop:
    white: 0.26
    black: 0.26
  knight:
    white: 0.21
    black: 0.21
  pawn:
    white: 0.36
    black: 0.36
  default:
    white: 0.0
    black: 0.0
craft-engine:
  enabled: false
  items:
    board: minechess:board
    book: minechess:tutorial_book
    highlight: minechess:highlight
    pieces:
      white:
        pawn: minechess:white_pawn
        knight: minechess:white_knight
        bishop: minechess:white_bishop
        rook: minechess:white_rook
        queen: minechess:white_queen
        king: minechess:white_king
      black:
        pawn: minechess:black_pawn
        knight: minechess:black_knight
        bishop: minechess:black_bishop
        rook: minechess:black_rook
        queen: minechess:black_queen
        king: minechess:black_king
